// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: proto/suiquote.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HoshimachiQuoteGen_GetRandomQuote_FullMethodName = "/suiquote.HoshimachiQuoteGen/GetRandomQuote"
)

// HoshimachiQuoteGenClient is the client API for HoshimachiQuoteGen service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HoshimachiQuoteGenClient interface {
	GetRandomQuote(ctx context.Context, in *SuiQuoteReq, opts ...grpc.CallOption) (*SuiQuoteResp, error)
}

type hoshimachiQuoteGenClient struct {
	cc grpc.ClientConnInterface
}

func NewHoshimachiQuoteGenClient(cc grpc.ClientConnInterface) HoshimachiQuoteGenClient {
	return &hoshimachiQuoteGenClient{cc}
}

func (c *hoshimachiQuoteGenClient) GetRandomQuote(ctx context.Context, in *SuiQuoteReq, opts ...grpc.CallOption) (*SuiQuoteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuiQuoteResp)
	err := c.cc.Invoke(ctx, HoshimachiQuoteGen_GetRandomQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HoshimachiQuoteGenServer is the server API for HoshimachiQuoteGen service.
// All implementations must embed UnimplementedHoshimachiQuoteGenServer
// for forward compatibility.
type HoshimachiQuoteGenServer interface {
	GetRandomQuote(context.Context, *SuiQuoteReq) (*SuiQuoteResp, error)
	mustEmbedUnimplementedHoshimachiQuoteGenServer()
}

// UnimplementedHoshimachiQuoteGenServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHoshimachiQuoteGenServer struct{}

func (UnimplementedHoshimachiQuoteGenServer) GetRandomQuote(context.Context, *SuiQuoteReq) (*SuiQuoteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandomQuote not implemented")
}
func (UnimplementedHoshimachiQuoteGenServer) mustEmbedUnimplementedHoshimachiQuoteGenServer() {}
func (UnimplementedHoshimachiQuoteGenServer) testEmbeddedByValue()                            {}

// UnsafeHoshimachiQuoteGenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HoshimachiQuoteGenServer will
// result in compilation errors.
type UnsafeHoshimachiQuoteGenServer interface {
	mustEmbedUnimplementedHoshimachiQuoteGenServer()
}

func RegisterHoshimachiQuoteGenServer(s grpc.ServiceRegistrar, srv HoshimachiQuoteGenServer) {
	// If the following call pancis, it indicates UnimplementedHoshimachiQuoteGenServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HoshimachiQuoteGen_ServiceDesc, srv)
}

func _HoshimachiQuoteGen_GetRandomQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuiQuoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoshimachiQuoteGenServer).GetRandomQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HoshimachiQuoteGen_GetRandomQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoshimachiQuoteGenServer).GetRandomQuote(ctx, req.(*SuiQuoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// HoshimachiQuoteGen_ServiceDesc is the grpc.ServiceDesc for HoshimachiQuoteGen service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HoshimachiQuoteGen_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "suiquote.HoshimachiQuoteGen",
	HandlerType: (*HoshimachiQuoteGenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRandomQuote",
			Handler:    _HoshimachiQuoteGen_GetRandomQuote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/suiquote.proto",
}
